apiVersion: v1
kind: Secret
metadata:
  name: print-secret
type: Opaque
data:
  greeting: V2FybSBncmVldGluZ3MgdG8=
  honorific: VGhlIE1vc3QgSG9ub3JhYmxl
  name: U2VjcmV0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-secret-greeting
  labels:
    app: print
spec: 
  selector:
    matchLabels:
      app: print
  template:
    metadata:
      labels:
        app: print
    spec:
      containers:
      - name: configmap-env-print-demo
        image: bash
        env:
        - name: GREETING
          valueFrom:
            secretKeyRef:
              name: print-secret
              key: greeting
        - name: HONORIFIC
          valueFrom:
            secretKeyRef:
              name: print-secret
              key: honorific
        - name: NAME
          valueFrom:
            secretKeyRef:
              name: print-secret
              key: name
        command: ["echo"]
        args: ["$(GREETING) $(HONORIFIC) $(NAME)"]